const CHAPTERS = {
1:{title:"Prophecies Are Fulfilled",subtitle:"Jesus is the promised Saviour",slides:[
{k:"CHAPTER 1 • STORY",t:"Jesus is the promised Saviour",sub:"Long before Jesus was born, God’s people were waiting for a Saviour.",body:"Balaam spoke about a star and a ruler rising from Israel. Isaiah spoke about a virgin who would give birth to a son called Immanuel. At the Annunciation, Angel Gabriel told Mary that she would give birth to Jesus, the Son of God. Mary trusted God and accepted God’s plan.",m:"PROMISE → ANNUNCIATION → NATIVITY"},
{k:"THE PROPHECIES",t:"God’s promise began long before Jesus’ birth",sub:"The lesson names several Old Testament prophecies connected with the promised Saviour.",body:"• Genesis 3:15 — an early promise connected with salvation.<br>• Moses’ prophecy.<br>• Balaam’s prophecy — a star would come out of Jacob and a ruler would rise from Israel.<br>• Isaiah 7:14 — a virgin would bear a son called Immanuel.",m:"BALAAM = STAR + RULER • ISAIAH = VIRGIN + IMMANUEL"},
{k:"THE ANNUNCIATION",t:"Gabriel brings God’s message to Mary",sub:"Angel Gabriel announced Jesus’ birth to Mary.",body:"Gabriel told Mary that she would become the mother of Jesus, the Son of God. Mary accepted God’s plan with faith and humility. Her response is remembered in Luke 1:38: she accepted her role as the servant of the Lord.",m:"MARY = YES TO GOD"},
{k:"THE NATIVITY",t:"Jesus is born in Bethlehem",sub:"Mary and Joseph went to Bethlehem in connection with the census ordered by Emperor Augustus.",body:"Jesus was born in Bethlehem. There was no place for Mary and Joseph in the inn, so Mary laid Jesus in a manger. The Nativity is the birth of Jesus, the promised Saviour.",m:"BETHLEHEM = BIRTH • MANGER = NO ROOM"},
{k:"THE SHEPHERDS",t:"The good news reaches the shepherds",sub:"Angels announced the birth of the Saviour to shepherds.",body:"The angel announced good news of great joy: a Saviour, the Messiah and Lord, had been born in the city of David. The shepherds hurried to Bethlehem, saw Jesus, and glorified and praised God.",m:"SHEPHERDS = HEARD → HURRIED → PRAISED"},
{k:"THE WISE MEN",t:"They follow the star",sub:"Wise men came from the East and followed the star.",body:"The wise men found Jesus, knelt down, paid Him homage and offered gifts. Their three gifts were <b>gold, frankincense and myrrh</b>.",m:"GOLD • FRANKINCENSE • MYRRH"},
{k:"ANNUNCIATION–NATIVITY",t:"A season of God’s saving plan",sub:"The Church remembers the events surrounding Jesus’ birth and childhood.",body:"The Annunciation Season is the first liturgical season and lasts four weeks. In Syriac it is called <b>Subara</b>, meaning announcement or declaration. Annunciation and Nativity commemorate God’s saving plan and the events surrounding Jesus’ birth and childhood.",m:"SUBARA = ANNOUNCEMENT / DECLARATION"},
{k:"KEY TERMS",t:"Words Sam should recognise",sub:"Use the keyword as the first clue when answering.",body:"<b>Prophecy</b> • Saviour • Annunciation • Gabriel • Mary • Joseph • Bethlehem • manger • shepherds • wise men • gold • frankincense • myrrh • B.C. • A.D. • Subara • Nativity.<br><br>B.C. refers to the period before Christ. A.D. refers to the period after Christ in the textbook’s presentation.",m:"KEYWORD → MAIN IDEA → SUPPORTING DETAIL"},
{k:"BIBLE CONNECTION",t:"Important Bible references",sub:"These references belong to the lesson.",body:"<b>Luke 1:38</b> — Mary’s response.<br><b>Luke 2:1–20</b> — Nativity and shepherds.<br><b>Matthew 2:1–12</b> — wise men.<br><b>Matthew 1:18–2:23</b> — Jesus’ birth and early life.",m:"Know the reference connected with the clue."},
{k:"QUESTION PRACTICE",t:"Important questions — Part 1",sub:"Answer in one or two clear sentences.",body:"<b>Who appeared to Mary?</b> Angel Gabriel.<br><b>What good news did Gabriel give?</b> Mary would become the mother of Jesus, the Son of God.<br><b>How did Mary respond?</b> She accepted God’s will humbly.<br><b>Why did Mary and Joseph go to Bethlehem?</b> In connection with Emperor Augustus’ census.<br><b>Why was Jesus laid in a manger?</b> There was no place for them in the inn.",m:"MARY → GABRIEL → BETHLEHEM → MANGER"},
{k:"QUESTION PRACTICE",t:"Important questions — Part 2",sub:"More answers from the lesson.",body:"<b>What message did the angel give the shepherds?</b> Good news of great joy: a Saviour, Messiah and Lord had been born.<br><b>What did the shepherds do?</b> They went quickly to Bethlehem, saw Jesus, and glorified and praised God.<br><b>What gifts did the wise men offer?</b> Gold, frankincense and myrrh.<br><b>What did the wise men do?</b> They knelt, paid homage and offered their gifts.",m:"SHEPHERDS = PRAISE • WISE MEN = HOMAGE"},
{k:"EXAM FOCUS",t:"What must be remembered?",sub:"The high-priority checklist from the preparation booklet.",body:"1. Prophecies → Annunciation → Nativity → Shepherds → Wise Men → Annunciation/Nativity seasons.<br>2. Gold, frankincense, myrrh.<br>3. Mary, Joseph, Gabriel, Augustus, Bethlehem, shepherds, wise men.<br>4. Luke 1:38.<br>5. Major salvific events include creation, sin and its results, God’s saving action in Old Testament history, prophecies, and events around Jesus’ birth and early life.",m:"Understand the story; remember the key words."},
{k:"5-MINUTE REVISION",t:"The whole chapter in one breath",sub:"Read this before practice.",body:"God promised a Saviour. Prophets pointed towards Him. Gabriel announced Jesus to Mary. Mary said yes to God. Jesus was born in Bethlehem and laid in a manger. Angels announced Him to shepherds. Wise men followed the star, worshipped Jesus and offered gold, frankincense and myrrh.",m:"JESUS = PROMISED SAVIOUR • MARY = YES • BETHLEHEM = BIRTH • SHEPHERDS = HEARD • WISE MEN = WORSHIPPED"},
{k:"FINAL MEMORY",t:"Chapter 1 master chain",sub:"Say this without looking.",body:"<div class='chain'>PROPHECIES → ANNUNCIATION → NATIVITY → SHEPHERDS → WISE MEN</div><p><b>Main message:</b> Jesus is the promised Saviour, Lord and King. We should welcome Him, worship Him and prepare our hearts for Him.</p>",m:"GOLD • FRANKINCENSE • MYRRH • LUKE 1:38"}]},
2:{title:"The Lamb of God Who Takes Away the Sins of the World",subtitle:"Jesus is the Lamb of God and Light of the World",slides:[
{k:"CHAPTER 2 • STORY",t:"John prepares the way",sub:"John the Baptist was sent by God to prepare people to receive Jesus.",body:"John was the son of Zechariah and Elizabeth and a relative of Mary. He preached repentance and baptized people in the River Jordan. His work was to prepare people for Jesus.",m:"JOHN PREPARES → JESUS IS REVEALED"},
{k:"JESUS’ BAPTISM",t:"Jesus comes to the Jordan",sub:"Jesus came to John to be baptized and to fulfil God’s plan.",body:"Jesus was without sin, yet He accepted baptism in obedience to God’s plan. When Jesus came up from the water, the heavens opened. The Holy Spirit descended like a dove, and the Father’s voice was heard.",m:"JORDAN → BAPTISM → HEAVENS → SPIRIT → FATHER"},
{k:"THE TRINITY",t:"Father, Son and Holy Spirit",sub:"The Holy Trinity was revealed at Jesus’ baptism.",body:"The <b>Son</b> was baptized. The <b>Holy Spirit</b> descended like a dove. The <b>Father</b> spoke from heaven. Christian faith teaches one God in three Persons: Father, Son and Holy Spirit.",m:"FATHER SPEAKS • SON IS BAPTIZED • SPIRIT DESCENDS"},
{k:"JOHN REVEALS JESUS",t:"“Lamb of God”",sub:"John pointed people towards Jesus.",body:"John called Jesus the <b>Lamb of God who takes away the sin of the world</b>. John witnessed that Jesus is the Son of God. Like John, we are called to introduce Jesus to others and witness to Him.",m:"JOHN = PREPARES + POINTS TO JESUS"},
{k:"CHRIST",t:"What does “Christ” mean?",sub:"A key word from the lesson.",body:"<b>Christ</b> means <b>“the anointed.”</b> The lesson connects Jesus’ identity with His baptism, His mission and His revelation as the Son of God.",m:"CHRIST = THE ANOINTED"},
{k:"DENEHA",t:"Epiphany — Deneha",sub:"A feast connected with the revelation of Jesus.",body:"<b>Deneha</b> is the Feast of Epiphany and is celebrated on <b>January 6</b>. Deneha means <b>sunrise or revelation</b>. In the Syro-Malabar tradition, it is connected with the light of Christ and traditions of baptismal remembrance.",m:"DENEHA = JANUARY 6 = EPIPHANY = SUNRISE / REVELATION"},
{k:"LIGHT OF THE WORLD",t:"Jesus brings light",sub:"Jesus is the Light of the World.",body:"Jesus leads people out of the darkness of sin and guides them towards God’s truth and life. John’s example teaches us to introduce Jesus to others and witness to Him.",m:"JESUS = LIGHT OF THE WORLD"},
{k:"BIBLE CONNECTION",t:"Important Bible references",sub:"Know which reference belongs to which idea.",body:"<b>Matthew 3:13–17</b> — Jesus’ baptism.<br><b>John 1:29–34</b> — John’s witness and “Lamb of God.”<br><b>John 8:12</b> — Jesus as the Light of the World.",m:"BAPTISM • LAMB OF GOD • LIGHT"},
{k:"QUESTION PRACTICE",t:"Baptism questions",sub:"Important answers from the lesson.",body:"<b>Who was John?</b> Son of Zechariah and Elizabeth, sent to prepare people for Jesus.<br><b>What was John doing?</b> Preaching repentance and baptizing in the Jordan.<br><b>Why did Jesus come to John?</b> To be baptized and fulfil God’s plan.<br><b>What happened after Jesus came out of the water?</b> Heavens opened, Spirit descended like a dove, Father’s voice was heard.",m:"Remember the sequence, not isolated facts."},
{k:"QUESTION PRACTICE",t:"Identity questions",sub:"More important answers.",body:"<b>What did the Father say?</b> “This is my Son, the Beloved, with whom I am well pleased.”<br><b>What did John call Jesus?</b> Lamb of God who takes away the sin of the world.<br><b>What is the Trinity?</b> One God in three Persons: Father, Son and Holy Spirit.<br><b>What does Christ mean?</b> The anointed.",m:"SON • SPIRIT • FATHER = TRINITY"},
{k:"QUESTION PRACTICE",t:"Deneha and mission",sub:"Connect the terms to their meanings.",body:"<b>What is Deneha?</b> Feast of Epiphany celebrating the revelation of Jesus.<br><b>When?</b> January 6.<br><b>Meaning?</b> Sunrise or revelation.<br><b>What does Light of the World mean?</b> Jesus leads us from darkness of sin towards God’s truth and life.<br><b>What should we learn from John?</b> Introduce Jesus to others and witness to Him.",m:"REVELATION → LIGHT → WITNESS"},
{k:"EXAM FOCUS",t:"What must be remembered?",sub:"The chapter’s high-priority revision.",body:"Baptism sequence: Jesus comes to Jordan → John baptizes → heavens open → Spirit descends → Father’s voice.<br>John = prepares the way + points to Jesus.<br>Lamb of God = Jesus who takes away the sin of the world.<br>Deneha = January 6 = Epiphany = sunrise/revelation.<br>Key verse: John 8:12.",m:"JOHN PREPARES → BAPTISM → SPIRIT → FATHER → REVELATION"},
{k:"FINAL MEMORY",t:"Chapter 2 master chain",sub:"Say it without looking.",body:"<div class='chain'>JOHN PREPARES → JESUS IS BAPTIZED → SPIRIT DESCENDS → FATHER SPEAKS → JOHN REVEALS JESUS → DENEHA</div><p>Jesus is the Son of God, the Lamb of God and the Light of the World.</p>",m:"FATHER • SON • HOLY SPIRIT"}]},
3:{title:"Jesus Who Overcame Temptations",subtitle:"God’s Word, prayer and self-control give strength",slides:[
{k:"CHAPTER 3 • STORY",t:"Forty days in the wilderness",sub:"Before beginning His public life, Jesus spent forty days fasting and praying.",body:"Jesus became hungry, and Satan tempted Him. Jesus answered each temptation with God’s Word. He did not misuse His divine power for selfish purposes. Satan left, and angels came to serve Jesus.",m:"40 DAYS → 3 TEMPTATIONS → JESUS WINS"},
{k:"TEMPTATION 1",t:"Turn stones into bread",sub:"Satan attacked Jesus’ hunger.",body:"Satan tempted Jesus to turn stones into bread. Jesus answered from Scripture that we do not live by bread alone, but by every word that comes from the mouth of God.",m:"BREAD → GOD’S WORD"},
{k:"TEMPTATION 2",t:"Test God",sub:"Satan tempted Jesus to throw Himself down from the temple.",body:"Jesus refused to test God. He answered that we must not put the Lord our God to the test.",m:"TEST GOD? → NO. TRUST GOD."},
{k:"TEMPTATION 3",t:"Worship Satan",sub:"Satan offered Jesus the kingdoms of the world.",body:"Satan offered worldly power if Jesus would worship him. Jesus rejected the offer, commanded Satan to go away, and said that we must worship the Lord our God and serve only Him.",m:"WORLDLY POWER → WORSHIP GOD ONLY"},
{k:"HOW JESUS WON",t:"God’s Word gives strength",sub:"Jesus overcame temptation through spiritual strength.",body:"The lesson connects victory over temptation with <b>abstinence, fasting, prayer and the Word of God</b>. Jesus never used His divine power for selfish purposes.",m:"WORD + FASTING + ABSTINENCE + PRAYER = SPIRITUAL STRENGTH"},
{k:"PRAYER",t:"What is prayer?",sub:"A simple definition to remember.",body:"Prayer is <b>conversation with God</b>. Prayer strengthens our relationship with God and helps us resist temptation.",m:"PRAYER = CONVERSATION WITH GOD"},
{k:"ACTS OF MERCY",t:"Strength is also lived out",sub:"The lesson connects spiritual life with acts of mercy.",body:"Acts of mercy include helping the sick, helping the poor and supporting charitable works. Self-denial and acts of mercy help us grow spiritually.",m:"HELP THE SICK • HELP THE POOR • SUPPORT GOOD WORKS"},
{k:"ABSTINENCE",t:"Periods of abstinence",sub:"The booklet includes these Syro-Malabar tradition points.",body:"The Syro-Malabar tradition remembers several periods of abstinence, including <b>50 days before Easter</b> and <b>25 days before Christmas</b>.",m:"50 BEFORE EASTER • 25 BEFORE CHRISTMAS"},
{k:"LENT",t:"A season of repentance",sub:"Lent is the fourth liturgical season.",body:"Lent recalls Jesus’ fasting and prayer in the wilderness. It is a time of fasting, prayer, repentance and preparation for Easter. The first Sunday of Lent is called <b>Pethurtha</b> in the textbook.",m:"LENT = 4TH SEASON → REPENTANCE → EASTER"},
{k:"HOLY WEEK",t:"The journey to Easter",sub:"Holy Week is the last week of Lent.",body:"Holy Week begins with <b>Palm Sunday</b> and leads through <b>Holy Thursday → Good Friday → Holy Saturday → Easter Sunday</b>. Good Friday remembers the passion, crucifixion and death of Jesus. Easter Sunday celebrates His Resurrection.",m:"PALM → THURSDAY → GOOD FRIDAY → HOLY SATURDAY → EASTER"},
{k:"BIBLE CONNECTION",t:"Important Bible references",sub:"The temptation story is connected with these Gospel passages.",body:"<b>Matthew 4:1–11</b> and <b>Luke 4:1–13</b> describe Jesus’ temptations. <b>Matthew 4:4</b> is the key verse highlighted in the lesson.",m:"KNOW THE REFERENCE + TEMPTATION ORDER"},
{k:"QUESTION PRACTICE",t:"The three temptations",sub:"Learn the questions and the answer pattern.",body:"<b>How long?</b> Forty days and forty nights.<br><b>First?</b> Turn stones into bread. <b>Answer:</b> We do not live by bread alone, but by God’s Word.<br><b>Second?</b> Throw Himself down and test God. <b>Answer:</b> Do not put the Lord your God to the test.<br><b>Third?</b> Worship Satan for worldly kingdoms. <b>Answer:</b> Worship and serve God only.",m:"BREAD → TEST GOD → WORSHIP SATAN"},
{k:"EXAM FOCUS",t:"What must be remembered?",sub:"High-priority revision.",body:"Three temptations in order. Three answers in order. Matthew 4:4. Word of God + fasting + abstinence + prayer = spiritual strength. Lent is the fourth season. Holy Week runs from Palm Sunday through Easter Sunday.",m:"SELF-CONTROL IS SPIRITUAL STRENGTH"},
{k:"FINAL MEMORY",t:"Chapter 3 master chain",sub:"Say this without looking.",body:"<div class='chain'>40 DAYS → BREAD → TEST GOD → WORSHIP SATAN → GOD’S WORD → PRAYER + FASTING + ABSTINENCE → LENT → EASTER</div><p>Jesus overcame temptation by remaining faithful to God.</p>",m:"WORSHIP GOD • SERVE GOD • TRUST GOD"}]},
4:{title:"Jesus Who Proclaims the Good News of the Kingdom of God",subtitle:"Jesus brings total liberation and reveals God’s Kingdom",slides:[
{k:"CHAPTER 4 • STORY",t:"Jesus announces His mission",sub:"At the beginning of His public life, Jesus went to the synagogue at Nazareth.",body:"Jesus read from the scroll of the prophet Isaiah. The passage spoke about good news to the poor, freedom for captives, sight for the blind, freedom for the oppressed and the year of the Lord’s favour. Jesus said that this Scripture had been fulfilled in their hearing.",m:"POOR → BONDAGE → BLIND → OPPRESSED → YEAR OF THE LORD"},
{k:"FIVE MISSION ASPECTS",t:"Jesus brings total liberation",sub:"Learn the five parts as one chain.",body:"1. Good News to the poor.<br>2. Liberation of those in bondage.<br>3. Sight for the blind.<br>4. Freedom for the oppressed.<br>5. The year acceptable to the Lord.",m:"5 MISSION ASPECTS = GOOD NEWS + FREEDOM"},
{k:"POOR IN SPIRIT",t:"Who are the “poor in spirit”?",sub:"A key meaning from the lesson.",body:"The “poor in spirit” are those who depend completely on <b>God’s mercy and providence</b> instead of relying on wealth or material power.",m:"POOR IN SPIRIT = DEPEND ON GOD"},
{k:"LIBERATION",t:"Jesus frees people from bondage",sub:"Liberation is more than physical freedom.",body:"Jesus freed people from <b>sin, sickness, spiritual bondage and social evils</b>. He led people towards freedom as children of God.",m:"SIN • SICKNESS • SPIRITUAL BONDAGE • SOCIAL EVILS"},
{k:"BLINDNESS",t:"Physical and spiritual blindness",sub:"Jesus healed blindness and challenged blindness of the heart and mind.",body:"Jesus healed the man born blind. He also challenged spiritual blindness such as <b>ignorance, injustice, exploitation and falsehood</b> by teaching truth and wisdom.",m:"BLINDNESS CAN BE PHYSICAL OR SPIRITUAL"},
{k:"YEAR OF THE LORD",t:"A society shaped by mercy and justice",sub:"The lesson explains the meaning behind this phrase.",body:"“The year acceptable to the Lord” describes a society where <b>mercy, justice, equality, sharing and freedom</b> replace debt, injustice, hatred and oppression.",m:"MERCY • JUSTICE • EQUALITY • SHARING • FREEDOM"},
{k:"KINGDOM OF GOD",t:"What is God’s Kingdom?",sub:"Jesus revealed the Kingdom through His life.",body:"The Kingdom of God is a state or community where <b>God is Father</b>, people live as brothers and sisters, and His will is lived through justice, peace, joy, love and sharing.",m:"GOD = FATHER • PEOPLE = BROTHERS + SISTERS"},
{k:"ST PAUL",t:"Justice, peace and joy",sub:"A key phrase to remember.",body:"St Paul teaches that the Kingdom of God is not about food and drink, but about <b>justice, peace and joy in the Holy Spirit</b>.",m:"JUSTICE + PEACE + JOY"},
{k:"HOW JESUS REVEALED IT",t:"Words, deeds, miracles and presence",sub:"The Kingdom became visible through Jesus.",body:"Jesus revealed the Kingdom through His <b>words, deeds, miracles and presence</b>. He forgave sins and healed the paralytic, showing authority over sin and sickness.",m:"WORDS • DEEDS • MIRACLES • PRESENCE"},
{k:"THE CHURCH",t:"The Church continues the mission",sub:"The lesson connects Jesus’ mission with the Church.",body:"The Church works to establish the values of God’s Kingdom on earth through its <b>presence, prayer and works</b>. The Church is called to receive, live and share the Good News.",m:"RECEIVE → LIVE → SHARE"},
{k:"THE FOUR GOSPELS",t:"Matthew • Mark • Luke • John",sub:"The first four books of the New Testament.",body:"The four Gospels are <b>Matthew, Mark, Luke and John</b>. They record Jesus’ teaching and works and are the first four books of the New Testament.",m:"MATTHEW → MARK → LUKE → JOHN"},
{k:"BIBLE CONNECTION",t:"Important references",sub:"Know the references linked with the lesson.",body:"<b>Luke 4:16–21</b> — Jesus’ mission at Nazareth.<br><b>Mark 2:1–12</b> — healing of the paralytic.<br><b>John 9</b> — man born blind.<br><b>Mark 1:14–15</b> — proclamation of the Kingdom.<br><b>Matthew 7:21</b> — doing the Father’s will.",m:"MISSION • LIBERATION • KINGDOM"},
{k:"QUESTION PRACTICE",t:"Mission questions",sub:"High-priority answers.",body:"<b>Which book was given to Jesus?</b> The scroll of Isaiah.<br><b>What did Jesus announce?</b> Good news to the poor, release to captives, sight to the blind, freedom to the oppressed and the year of the Lord’s favour.<br><b>Who are the poor in spirit?</b> Those who depend on God’s mercy and providence.<br><b>How did Jesus liberate people?</b> From sin, sickness, spiritual bondage and social evils.",m:"FIVE MISSION ASPECTS"},
{k:"QUESTION PRACTICE",t:"Kingdom questions",sub:"Connect the ideas.",body:"<b>How did Jesus remove blindness?</b> By healing physical blindness and opposing spiritual blindness through truth and wisdom.<br><b>How was the Kingdom revealed?</b> Through words, deeds, miracles and presence.<br><b>What is the Kingdom?</b> A community of justice, peace, joy, love and sharing under God the Father.<br><b>What does St Paul say?</b> Justice, peace and joy in the Holy Spirit.<br><b>What is the Church’s mission?</b> Establish Kingdom values through presence, prayer and works.",m:"KINGDOM = JUSTICE + PEACE + JOY + LOVE + SHARING"},
{k:"EXAM FOCUS",t:"What must be remembered?",sub:"The chapter’s high-priority checklist.",body:"Memorise the five mission aspects. Know “poor in spirit.” Know physical vs spiritual blindness. Know the Kingdom definition. Know St Paul’s “justice, peace and joy in the Holy Spirit.” Know the four Gospels and that they are the first four New Testament books. Key verse: Matthew 7:21.",m:"POOR → BONDAGE → BLIND → OPPRESSED → KINGDOM"},
{k:"FINAL MEMORY",t:"Chapter 4 master chain",sub:"Say it without looking.",body:"<div class='chain'>GOOD NEWS → LIBERATION → SIGHT → FREEDOM → YEAR OF THE LORD → KINGDOM OF GOD → CHURCH</div><p>Jesus is the total liberator and reveals God’s Kingdom.</p>",m:"RECEIVE • LIVE • SHARE THE GOOD NEWS"}]},
5:{title:"Jesus Who Revealed the Glory of God",subtitle:"Jesus reveals His divine glory through signs and miracles",slides:[
{k:"CHAPTER 5 • STORY",t:"Signs that reveal Jesus’ glory",sub:"The lesson follows four major miracles.",body:"At Cana Jesus changed water into wine. On the Sea of Galilee He calmed a dangerous storm. At Bethzatha He healed a man ill for thirty-eight years. At Bethany He raised Lazarus from the dead. These signs reveal Jesus’ divine glory and call us to believe in Him.",m:"CANA → STORM → BETHZATHA → LAZARUS"},
{k:"CANA",t:"Water becomes wine",sub:"Jesus and His disciples attended a wedding in Cana in Galilee.",body:"The family ran out of wine. Mary told Jesus, “They have no wine.” She then told the attendants, <b>“Do whatever he tells you.”</b> Jesus changed water into wine. This was the beginning of His signs and revealed His glory.",m:"CANA = WATER → WINE → FIRST SIGN"},
{k:"MARY’S TRUST",t:"“Do whatever he tells you”",sub:"Mary showed complete trust in Jesus.",body:"Mary’s trust is an important attitude in the lesson. She brought the problem to Jesus and told the attendants to obey Him.",m:"MARY = TRUST"},
{k:"THE STORM",t:"“Peace! Be still!”",sub:"Jesus and His disciples crossed the Sea of Galilee.",body:"A great storm arose while Jesus slept. Jesus rebuked the wind and sea and brought calm. The disciples were filled with awe because even the wind and sea obeyed Him.",m:"STORM → JESUS SPEAKS → CALM"},
{k:"BETHZATHA",t:"A man ill for thirty-eight years",sub:"Jesus met a man at the pool of Bethzatha in Jerusalem.",body:"The man had been ill for <b>thirty-eight years</b>. Jesus told him, <b>“Stand up, take your mat and walk.”</b> The man was healed.",m:"BETHZATHA = 38 YEARS → HEALED"},
{k:"LAZARUS",t:"“I am the resurrection and the life”",sub:"Jesus went to Bethany after Lazarus had died.",body:"Jesus told Martha, <b>“I am the resurrection and the life.”</b> At the tomb Jesus prayed to His Father and called Lazarus to come out. Lazarus came out alive. The lesson notes that Lazarus had been in the tomb for four days.",m:"BETHANY → LAZARUS → 4 DAYS → LIFE"},
{k:"WHY MIRACLES MATTER",t:"Signs reveal divine glory",sub:"The miracles are not just amazing events.",body:"The miracles are <b>signs</b> that reveal Jesus’ divine glory and strengthen faith. They call people to believe in Him and proclaim His glory.",m:"MIRACLE = SIGN → GLORY → FAITH"},
{k:"PROVIDENCE",t:"Trust Jesus in daily life",sub:"The lesson applies the miracles to everyday life.",body:"The calming of the storm teaches that whatever hardship we face, we can remain secure when Jesus is with us. The lesson also teaches us to see God’s providence in both victories and defeats and to trust Jesus.",m:"VICTORY OR DEFEAT → TRUST GOD’S PROVIDENCE"},
{k:"BIBLE CONNECTION",t:"Four key references",sub:"Match each sign with its reference.",body:"<b>John 2:1–11</b> — Cana.<br><b>Mark 4:35–41</b> — calming the storm.<br><b>John 5:1–15</b> — Bethzatha.<br><b>John 11:1–44</b> — Lazarus.",m:"JOHN 2 • MARK 4 • JOHN 5 • JOHN 11"},
{k:"KEY NUMBERS",t:"Numbers worth remembering",sub:"The exam focus highlights these details.",body:"<b>Six</b> stone jars at Cana.<br><b>Thirty-eight years</b> — the man at Bethzatha had been ill.<br><b>Four days</b> — Lazarus had been in the tomb.",m:"6 JARS • 38 YEARS • 4 DAYS"},
{k:"QUESTION PRACTICE",t:"Cana and the storm",sub:"Important answers.",body:"<b>What problem occurred?</b> The family ran out of wine.<br><b>What did Mary tell Jesus?</b> They have no wine.<br><b>What did Mary tell the attendants?</b> Do whatever he tells you.<br><b>What did Jesus do?</b> Changed water into wine.<br><b>What happened in the storm?</b> A great storm arose; Jesus rebuked the wind and sea and brought calm.",m:"CANA → STORM"},
{k:"QUESTION PRACTICE",t:"Bethzatha and Lazarus",sub:"More important answers.",body:"<b>How long was the man ill?</b> Thirty-eight years.<br><b>What did Jesus tell him?</b> Stand up, take your mat and walk.<br><b>What did Jesus tell Martha?</b> I am the resurrection and the life.<br><b>What did Jesus do at the tomb?</b> Prayed to His Father and called Lazarus out.<br><b>What happened?</b> Lazarus came out alive.",m:"38 YEARS → WALK • 4 DAYS → LIFE"},
{k:"WHY DELAY?",t:"Lazarus and God’s glory",sub:"The lesson explains why Jesus delayed going to Bethany.",body:"The lesson explains that the illness was for the <b>glory of God</b> and so that the Son of God would be glorified. The event became a sign calling people to faith.",m:"GLORY OF GOD → FAITH"},
{k:"EXAM FOCUS",t:"What must be remembered?",sub:"High-priority revision.",body:"Know the four miracles in order: Cana → Storm → Bethzatha → Lazarus. Know Jesus, Mary, disciples, Martha, Mary and Lazarus. Know 6 jars, 38 years and 4 days. Know all four Bible references. Memorise John 11:25: “I am the resurrection and the life.”",m:"SIGNS → DIVINE GLORY → BELIEF"},
{k:"FINAL MEMORY",t:"Chapter 5 master chain",sub:"Say this without looking.",body:"<div class='chain'>CANA → STORM → BETHZATHA → LAZARUS → JESUS REVEALS HIS GLORY</div><p>Jesus’ signs reveal His divine glory and strengthen faith.</p>",m:"TRUST • BELIEVE • PROCLAIM HIS GLORY"}]}};

const id=Number(document.body.dataset.chapter||new URLSearchParams(location.search).get("chapter")||1);
const chapter=CHAPTERS[id]||CHAPTERS[1];
let current=0;
const host=document.getElementById("pptHost"),counter=document.getElementById("pptCounter"),progress=document.getElementById("pptProgress");
document.getElementById("pptTitle").textContent="CHAPTER "+id+" • CATECHISM";
document.getElementById("pptSubtitle").textContent=chapter.title;
function render(){
 const s=chapter.slides[current];
 host.innerHTML='<article class="ppt-slide"><div class="ppt-kicker">'+s.k+'</div><h1>'+s.t+'</h1><p class="ppt-sub">'+s.sub+'</p><div class="ppt-body">'+s.body+'</div><div class="ppt-memory">🧠 '+s.m+'</div></article>';
 counter.textContent=(current+1)+" / "+chapter.slides.length;
 progress.style.width=((current+1)/chapter.slides.length*100)+"%";
 document.getElementById("pptPrev").disabled=current===0;
 document.getElementById("pptNext").disabled=current===chapter.slides.length-1;
}
function move(n){current=Math.max(0,Math.min(chapter.slides.length-1,current+n));render();window.scrollTo({top:0,behavior:"smooth"});}
document.getElementById("pptPrev").onclick=()=>move(-1);
document.getElementById("pptNext").onclick=()=>move(1);
document.addEventListener("keydown",e=>{if(e.key==="ArrowLeft")move(-1);if(e.key==="ArrowRight")move(1);if(e.key.toLowerCase()==="f")toggleFull();});
function toggleFull(){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.();}
document.getElementById("pptFull").onclick=toggleFull;
render();