const levels=[
{n:1,title:"Hello, Friends!",tag:"START HERE",icon:"👋",goal:"Say hello, use a person's name, and answer a simple greeting.",phrases:["Hi, Edwin!","Hello, Alan!","How are you?","I'm good. How are you?","See you later!"],scenarios:[["Before class","Sam: “Hi, Alvin!”<br>Alvin: “Hi, Sam!”<br>Sam: “How are you?”"],["At the school gate","Sam: “Hello, Devamsh!”<br>Devamsh: “Hi!”<br>Sam: “Ready for class?”"]],mission:"Say hello to one familiar person each school day."},
{n:2,title:"Ask One Question",tag:"STARTING A CHAT",icon:"❓",goal:"Move from greeting to a simple question.",phrases:["What are you doing?","What are you reading?","Did you finish the work?","Which game do you like?","What period is next?"],scenarios:[["At the desk","Sam: “Hi, Ayan. What are you doing?”<br>Ayan: “I'm drawing.”<br>Sam: “Oh, nice!”"],["Between periods","Sam: “Hi, Einstein. Which period is next?”<br>Einstein: “Science.”<br>Sam: “Great!”"]],mission:"After saying hello, ask one easy question."},
{n:3,title:"Join the Conversation",tag:"JOINING FRIENDS",icon:"🧩",goal:"Enter a conversation politely instead of waiting for someone to speak first.",phrases:["What are you talking about?","Can I join you?","What are you playing?","Can I play too?","Tell me about it."],scenarios:[["Friends are talking","Sam: “Hi, Edwin. What are you talking about?”<br>Edwin: “We're talking about the match.”<br>Sam: “Oh! I watched it too.”"],["A game is starting","Sam: “Can I join you?”<br>Friend: “Sure!”<br>Sam: “Thanks! What should I do?”"]],mission:"Find one natural moment to join a group activity."},
{n:4,title:"School Talk",tag:"CLASSROOM LIFE",icon:"🎒",goal:"Talk about homework, lessons, teachers, lunch and the school day.",phrases:["Did you understand this?","What did we get for homework?","Which subject do you like?","What did you bring for lunch?","Are you ready for the test?"],scenarios:[["After a lesson","Sam: “Did you understand this question?”<br>Alan: “Yes, I think so.”<br>Sam: “Can you explain it to me?”"],["Lunch break","Sam: “What did you bring for lunch?”<br>Friend: “Chapati and curry.”<br>Sam: “Sounds good!”"]],mission:"Use one school topic to start a conversation."},
{n:5,title:"Friends & Shared Interests",tag:"KEEP IT GOING",icon:"⚽",goal:"Find something you both like and add a follow-up sentence.",phrases:["Do you like football?","Which team do you support?","I like that too.","Really? Tell me more.","What do you think?"],scenarios:[["Talking about a game","Sam: “Do you like football?”<br>Friend: “Yes!”<br>Sam: “Me too. Which team do you like?”"],["A favourite topic","Sam: “I like space.”<br>Friend: “Me too.”<br>Sam: “What's your favourite planet?”"]],mission:"Ask a follow-up question instead of ending after one answer."},
{n:6,title:"Picnic, Tour & Play",tag:"OUTSIDE SCHOOL",icon:"🚌",goal:"Use English naturally during trips, games and shared activities.",phrases:["Are you coming on the trip?","Where are we going?","Do you want to sit here?","Let's play together.","That was fun!"],scenarios:[["School trip","Sam: “Are you coming on the trip?”<br>Friend: “Yes.”<br>Sam: “Great! What are you most excited about?”"],["At a picnic","Sam: “Do you want to play?”<br>Friend: “Sure.”<br>Sam: “Let's choose a game.”"]],mission:"Start one conversation during a trip, break or playtime."},
{n:7,title:"Ask, Help & Reply",tag:"SOCIAL CONFIDENCE",icon:"🤝",goal:"Ask for help, respond to others and keep the interaction comfortable.",phrases:["Can you help me?","Could you show me?","Sure, no problem.","Thanks for helping me.","You're welcome!"],scenarios:[["Need help","Sam: “Edwin, can you help me with this?”<br>Edwin: “Sure.”<br>Sam: “Thanks!”"],["Someone asks Sam something","Friend: “Are you coming?”<br>Sam: “Yes, I am.”<br>Sam: “What time are you leaving?”"]],mission:"Practice asking for help and saying thank you."},
{n:8,title:"Talk to Any Classmate",tag:"GIRLS & BOYS",icon:"🌈",goal:"Treat every classmate as a possible conversation partner and use the same friendly starters.",phrases:["Hi! How are you?","What are you working on?","Do you want to join us?","That's interesting.","Nice talking to you!"],scenarios:[["Class activity","Sam: “Hi! What are you working on?”<br>Classmate: “I'm making this chart.”<br>Sam: “That's nice. Can I see?”"],["Mixed group activity","Sam: “Do you want to join us?”<br>Classmate: “Okay.”<br>Sam: “Great! Let's start.”"]],mission:"Say hello to a classmate you do not usually talk with. No pressure — one sentence is enough."},
{n:9,title:"Family & Cousin Chats",tag:"AT HOME",icon:"🏡",goal:"Use conversation skills with cousins and family members of different ages.",phrases:["Hi, Jeswin! What are you doing?","Joe, do you want to play?","Sandra, what are you watching?","Chinnu, how was your day?","Zion, what are you playing with?"],scenarios:[["With older cousins","Sam: “Hi, Jeswin. What are you doing?”<br>Jeswin: “I'm watching a video.”<br>Sam: “Can I watch with you?”"],["With Sandra or Chinnu","Sam: “Hi! How was your day?”<br>Cousin: “Good.”<br>Sam: “What was the best part?”"]],mission:"Ask a cousin one question and respond to their answer."},
{n:10,title:"Real Conversation Builder",tag:"CONFIDENT SAM",icon:"⭐",goal:"Build a 3–5 turn conversation, ask a follow-up, and repair the conversation if needed.",phrases:["Really? Why?","What happened next?","I think so too.","Sorry, I didn't understand.","Can you say that again?","Anyway, see you tomorrow!"],scenarios:[["A full school chat","Sam: “Hi, Edwin! How was your day?”<br>Edwin: “Good. We had a science activity.”<br>Sam: “Really? What did you do?”<br>Edwin: “We made a model.”<br>Sam: “That sounds fun!”"],["When he gets stuck","Friend: “We're going after lunch.”<br>Sam: “Sorry, I didn't understand. After lunch?”<br>Friend: “Yes.”<br>Sam: “Okay, thanks!”"]],mission:"Have one 3–5 turn conversation. Success means trying, not being perfect."}
];
const n=Number(new URLSearchParams(location.search).get("level")||1);
const l=levels.find(x=>x.n===n)||levels[0];
document.title=`Level ${l.n} • ${l.title} • Sam`;
document.getElementById("levelRoot").innerHTML=`
<section class="level-hero-card">
 <div class="level-hero-icon">${l.icon}</div><p class="eyebrow">LEVEL ${l.n} • ${l.tag}</p><h1>${l.title}</h1><p>${l.goal}</p>
</section>
<section class="practice-block"><div class="block-heading"><span>💬</span><div><p class="eyebrow">READY PHRASES</p><h2>Try these sentences</h2></div></div><div class="phrase-grid">${l.phrases.map(p=>`<button class="phrase" type="button" data-say="${p.replace(/"/g,'&quot;')}" title="Tap to hear">🔊 ${p}</button>`).join("")}</div></section>
<section class="scenario-grid">${l.scenarios.map((s,i)=>`<article class="scenario-card"><span class="scenario-label">SCENARIO ${i+1}</span><h2>${s[0]}</h2><div class="dialogue">${s[1]}</div></article>`).join("")}</section>
<section class="mission-card"><span class="mission-icon">🎯</span><div><p class="eyebrow">TODAY'S TINY MISSION</p><h2>${l.mission}</h2><p>One small attempt counts. Sam does not have to speak perfectly or for a long time.</p></div></section>
<nav class="level-nav"><a href="communicate-level.html?level=${Math.max(1,l.n-1)}">← Previous</a><span>Level ${l.n} / 10</span><a href="communicate-level.html?level=${Math.min(10,l.n+1)}">Next →</a></nav>
`;
document.querySelectorAll("[data-say]").forEach(btn=>btn.addEventListener("click",()=>{if("speechSynthesis" in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(btn.dataset.say);u.lang="en-IN";u.rate=.82;u.pitch=1; speechSynthesis.speak(u)}}));
