const data={
1:{title:"Hallo! German Starter",tag:"A0",icon:"👋",goal:"Learn to greet people, say your name, count, and recognise your first everyday German words.",words:["hallo — hello","tschüss — bye","danke — thank you","bitte — please / you're welcome","ja — yes","nein — no","ich — I","du — you","eins — one","zwei — two","drei — three","rot — red","blau — blue","grün — green","gelb — yellow"],phrases:["Hallo! Ich heiße Sam. — Hello! My name is Sam.","Wie heißt du? — What is your name?","Wie geht's? — How are you?","Gut, danke! — Good, thank you!","Tschüss! Bis bald! — Bye! See you soon!"],grammar:"Start with ich (I) and du (you). Learn whole phrases before worrying about grammar rules.",mission:["Say your name in German.","Count from 1 to 10 aloud.","Greet three imaginary people.","Match five German words to their meanings.","Say one sentence using ich."]},
2:{title:"Meine Welt",tag:"A0+",icon:"🏠",goal:"Talk simply about yourself, family and where you are from.",words:["ich — I","du — you","er — he","sie — she","wir — we","Mutter — mother","Vater — father","Bruder — brother","Schwester — sister","Freund — friend (male)","Freundin — friend (female)","Kind — child"],phrases:["Ich bin Sam. — I am Sam.","Ich bin zwölf Jahre alt. — I am twelve years old.","Ich komme aus Indien. — I come from India.","Das ist meine Mutter. — This is my mother.","Wer ist das? — Who is that?"],grammar:"Meet sein (to be): ich bin, du bist, er/sie ist. Focus on recognising these forms.",mission:["Introduce yourself.","Say your age.","Name four family members.","Ask and answer Wer ist das?","Build three sentences with bin / bist / ist."]},
3:{title:"Schule & Dinge",tag:"A0+/A1",icon:"🎒",goal:"Name classroom objects and begin noticing German noun articles.",words:["Schule — school","Buch — book","Stift — pen","Tasche — bag","Tisch — table","Stuhl — chair","Heft — notebook","Lehrer — teacher (male)","Lehrerin — teacher (female)","Tür — door","Fenster — window"],phrases:["Das ist ein Buch. — This is a book.","Das ist eine Tasche. — This is a bag.","Wo ist mein Stift? — Where is my pen?","Hier! — Here!","Ich habe ein Buch. — I have a book."],grammar:"German nouns have grammatical gender. Start recognising der, die and das; learn each noun with its article.",mission:["Label ten objects.","Sort nouns you know into der/die/das.","Ask Wo ist...?","Use ein/eine with familiar nouns.","Make five Das ist... sentences."]},
4:{title:"Essen & Trinken",tag:"A1",icon:"🍎",goal:"Talk about favourite foods and make simple requests.",words:["Wasser — water","Milch — milk","Brot — bread","Apfel — apple","Banane — banana","Käse — cheese","Pizza — pizza","Saft — juice","Eis — ice cream","Kuchen — cake","Tee — tea","Schokolade — chocolate"],phrases:["Ich mag Pizza. — I like pizza.","Ich mag Äpfel. — I like apples.","Ich möchte Wasser. — I would like water.","Bitte ein Eis. — An ice cream, please.","Was möchtest du? — What would you like?"],grammar:"Learn mögen (to like) and the useful phrase ich möchte (I would like).",mission:["Name ten foods.","Say five likes.","Order a pretend snack.","Ask a friend what they want.","Build a tiny café dialogue."]},
5:{title:"Meine Woche",tag:"A1",icon:"📅",goal:"Talk about days, time and a simple daily routine.",words:["Montag — Monday","Dienstag — Tuesday","Mittwoch — Wednesday","Donnerstag — Thursday","Freitag — Friday","Samstag — Saturday","Sonntag — Sunday","heute — today","morgen — tomorrow","gestern — yesterday","Morgen — morning","Abend — evening"],phrases:["Heute ist Montag. — Today is Monday.","Ich stehe um sieben Uhr auf. — I get up at seven.","Ich gehe zur Schule. — I go to school.","Am Abend lese ich. — In the evening I read.","Wann? — When?"],grammar:"Build simple present-tense sentences and learn that German often places the verb early in a sentence.",mission:["Say all seven days.","Tell the time.","Describe your morning.","Describe three things you do each day.","Ask Wann...? and answer it."]},
6:{title:"Hobbys & Action",tag:"A1",icon:"⚽",goal:"Talk about hobbies and what you can or want to do.",words:["spielen — to play","lesen — to read","schwimmen — to swim","laufen — to run","singen — to sing","tanzen — to dance","Musik — music","Sport — sport","Film — film","Buch — book"],phrases:["Ich spiele gern Fußball. — I like playing football.","Ich lese gern. — I like reading.","Ich kann schwimmen. — I can swim.","Ich möchte Deutsch lernen. — I would like to learn German.","Was machst du gern? — What do you like doing?"],grammar:"Meet können (can) and möchten (would like). Notice that the second verb stays in its basic form.",mission:["Talk about three hobbies.","Use kann in three sentences.","Use möchte in three sentences.","Ask a hobby question.","Make a five-line mini dialogue."]},
7:{title:"Meine Stadt",tag:"A1",icon:"🗺️",goal:"Name places and understand simple directions.",words:["Stadt — city","Schule — school","Bahnhof — station","Park — park","Supermarkt — supermarket","Museum — museum","Straße — street","links — left","rechts — right","geradeaus — straight ahead"],phrases:["Wo ist der Bahnhof? — Where is the station?","Gehen Sie geradeaus. — Go straight ahead.","Links! — Left!","Rechts! — Right!","Der Park ist neben der Schule. — The park is next to the school."],grammar:"Start using simple location words such as in, neben, vor and hinter with familiar places.",mission:["Draw a tiny German town map.","Label five places.","Give three directions.","Ask for a place.","Describe where two places are."]},
8:{title:"Tiere, Wetter & Natur",tag:"A1",icon:"🐺",goal:"Describe animals, weather and the natural world.",words:["Hund — dog","Katze — cat","Vogel — bird","Pferd — horse","Elefant — elephant","Sonne — sun","Regen — rain","Schnee — snow","Wind — wind","warm — warm","kalt — cold","groß — big"],phrases:["Ich mag Hunde. — I like dogs.","Das Wetter ist schön. — The weather is nice.","Es regnet. — It is raining.","Der Hund ist groß. — The dog is big.","Heute ist es kalt. — Today it is cold."],grammar:"Use simple adjectives to describe nouns and practise es ist / es regnet for weather.",mission:["Name ten animals.","Describe three animals.","Give today's weather report.","Use five adjectives.","Make a four-sentence nature story."]},
9:{title:"Unterwegs",tag:"A1",icon:"🚆",goal:"Handle simple real-life situations: shopping, food and travel.",words:["Zug — train","Bus — bus","Ticket — ticket","Preis — price","Euro — euro","Restaurant — restaurant","Speisekarte — menu","Rechnung — bill","Zimmer — room","Hotel — hotel"],phrases:["Wie viel kostet das? — How much does that cost?","Ich möchte ein Ticket. — I would like a ticket.","Die Rechnung, bitte. — The bill, please.","Wo ist das Hotel? — Where is the hotel?","Ich habe eine Frage. — I have a question."],grammar:"Practise polite requests and begin noticing accusative forms such as ein Ticket / eine Frage.",mission:["Role-play a shop.","Buy a pretend ticket.","Order at a restaurant.","Ask the price of three things.","Create a travel dialogue."]},
10:{title:"A1 German Explorer",tag:"A1 Bridge",icon:"🏆",goal:"Bring everything together: understand familiar phrases, build short texts and speak with confidence.",words:["weil — because","aber — but","und — and","oder — or","auch — also","immer — always","manchmal — sometimes","heute — today","morgen — tomorrow","zusammen — together"],phrases:["Ich lerne Deutsch, weil es Spaß macht. — I learn German because it is fun.","Ich kann ein bisschen Deutsch sprechen. — I can speak a little German.","Kannst du mir helfen? — Can you help me?","Ich verstehe nicht. — I don't understand.","Kannst du das wiederholen? — Can you repeat that?"],grammar:"Review present tense, articles, basic word order, modal verbs, questions and everyday phrases.",mission:["Introduce yourself for one minute.","Read a short German text aloud.","Write eight connected sentences.","Have a five-question conversation.","Complete a personal A1-style challenge."]}
};
const level=Number(new URLSearchParams(location.search).get("level")||1);
const d=data[level]||data[1];
document.title=d.title+" • Study German";
document.getElementById("levelTitle").textContent="🇩🇪 "+d.title;
document.getElementById("levelBadge").textContent=d.tag;
document.getElementById("levelHero").innerHTML=`<span class="level-hero-icon">${d.icon}</span><p class="eyebrow">LEVEL ${level} • ${d.tag}</p><h1>${d.title}</h1><p>${d.goal}</p>`;
const missions=["🧠 Learn the words","💬 Speak the phrases","🔤 Notice the grammar","🎯 Do the mission"];
document.getElementById("lessonMissions").innerHTML=missions.map((m,i)=>`<article class="mission-card"><span>${m.split(" ")[0]}</span><h2>${m.substring(m.indexOf(" ")+1)}</h2><p>${i===0?d.words.map(x=>"<b>"+x+"</b>").join(" • "):i===1?d.phrases.map(x=>"<b>"+x+"</b>").join("<br>"):i===2?d.grammar:d.mission.map((x,j)=>(j+1)+". "+x).join("<br>")}</p></article>`).join("");
document.getElementById("phraseBox").innerHTML=`<div><p class="eyebrow">SAM’S SPEAKING BOOST</p><h2>Say these aloud 🎙️</h2><p>${d.phrases.join("<br>")}</p></div><div class="phrase-tip">⭐ Don’t wait until you know all the grammar. Say the useful phrases first.</div>`;
const resource=level<=3?"https://www.goethe.de/prj/dlp/en/teachingmaterials/series/a_glimpse_of_germany":"https://www.goethe.de/en/spr/ueb/ele.html";
document.getElementById("levelResource").innerHTML=`<strong>🌐 Extra practice for this level</strong><span>Goethe-Institut beginner material and exercises</span><a href="${resource}" target="_blank" rel="noopener">Open trusted practice →</a>`;