const DATA={
ruth:{name:"Ruth",chapters:{1:["Naomi loses her husband and sons","Ruth chooses to stay with Naomi","They arrive in Bethlehem at barley harvest"],2:["Ruth gleans in Boaz's field","Boaz notices Ruth","Ruth tells Naomi about Boaz"],3:["Naomi gives Ruth a plan","Ruth goes to Boaz at the threshing floor","Boaz promises to act as redeemer"],4:["Boaz meets the nearer relative","Boaz marries Ruth","Ruth and Boaz have a son named Obed"]}},
samuel:{name:"1 Samuel",chapters:{1:["Hannah prays at Shiloh","Samuel is born","Hannah dedicates Samuel to the Lord"],2:["Hannah praises God","Samuel serves at the sanctuary","Eli's sons are condemned for their wickedness"],3:["Samuel hears a voice at night","Eli realizes the Lord is calling him","Samuel receives a message from the Lord"],4:["The ark is taken by the Philistines","Eli dies after hearing the news","Phinehas's wife names her son Ichabod"],5:["The ark is placed beside Dagon","Dagon falls before the ark","Plagues strike the Philistine cities"],6:["The Philistines send the ark away","The ark reaches Beth-shemesh","The people respond to the returned ark"],7:["Israel puts away foreign gods","Samuel gathers the people at Mizpah","God gives Israel victory over the Philistines"]}},
ecclesiastes:{name:"Ecclesiastes",chapters:{1:["Everything is described as vanity","Generations come and go","The Teacher reflects on wisdom and knowledge"],2:["The Teacher tests pleasure","Great works and possessions are considered","Wisdom is compared with folly"],3:["There is a season for every activity","Human beings face limits","The Teacher reflects on God's ordering of time"],4:["The Teacher observes oppression","Two are better than one","A threefold cord is described as strong"],5:["The Teacher warns about careless words before God","Vows are treated seriously","Wealth does not guarantee satisfaction"],6:["A person may possess wealth without enjoying it","Human appetite is never fully satisfied","The limits of human knowledge are considered"]}},
john:{name:"Gospel according to John",chapters:{1:["The Word is introduced","John the Baptist bears witness","Jesus calls the first disciples"],2:["Jesus turns water into wine","Jesus goes to Jerusalem","Jesus cleanses the temple"],3:["Nicodemus visits Jesus at night","Jesus teaches about new birth","John the Baptist continues to testify"],4:["Jesus meets a Samaritan woman","Jesus offers living water","Many Samaritans believe"],5:["Jesus heals a man at Bethesda","The healing leads to controversy","Jesus speaks about his authority"],6:["Jesus feeds about five thousand people","Jesus walks on the sea","Jesus teaches about the bread of life"],7:["Jesus teaches at the Feast of Booths","People debate who Jesus is","Jesus speaks about living water"],8:["Jesus teaches in the temple","Jesus speaks about being the light of the world","A dispute arises about Abraham"],9:["Jesus gives sight to a man born blind","The Pharisees question the man","The man comes to believe in Jesus"],10:["Jesus teaches about the sheepfold","Jesus calls himself the good shepherd","Jesus speaks about his sheep"],11:["Lazarus becomes ill and dies","Jesus arrives at Bethany","Jesus calls Lazarus from the tomb"],12:["Mary anoints Jesus","Jesus enters Jerusalem","Jesus speaks about his coming death"]}},
galatians:{name:"Galatians",chapters:{1:["Paul introduces himself","Paul warns against a different gospel","Paul describes his calling"],2:["Paul describes his meeting with the apostles","Paul confronts Peter at Antioch","Paul explains justification by faith"],3:["Paul asks how the Galatians received the Spirit","Abraham is presented as a man of faith","The promise is discussed in relation to the law"],4:["Paul describes believers as heirs","Paul uses Hagar and Sarah as an illustration","Paul urges freedom from returning to slavery"],5:["Paul urges believers to stand firm in freedom","Love fulfills the law","The fruit of the Spirit is described"],6:["Believers are told to restore others gently","Paul teaches about sowing and reaping","Paul emphasizes the new creation"]}}
};
const p=new URLSearchParams(location.search),book=p.get("book")||"ruth",chapter=Number(p.get("chapter")||1),info=DATA[book],events=info?.chapters?.[chapter]||[];
const title=document.getElementById("quizTitle"),sub=document.getElementById("quizSubtitle"),area=document.getElementById("quizArea"),progress=document.getElementById("quizProgress");
title.textContent=(info?.name||"Bible")+" • Chapter "+chapter+" MCQ";sub.textContent="Choose one of four answers. The correct answer appears immediately after Sam selects.";
const all=Object.values(info?.chapters||{}).flat(),questions=events.map(correct=>{const distractors=all.filter(x=>x!==correct).sort(()=>Math.random()-.5).slice(0,3);return{q:"Which event is found in "+info.name+" Chapter "+chapter+"?",answer:correct,options:[correct,...distractors].sort(()=>Math.random()-.5)}});let index=0,score=0;
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function show(){progress.textContent="Question "+(index+1)+" of "+questions.length;const q=questions[index];area.innerHTML='<div class="mcq-question"><div class="mcq-number">QUESTION '+(index+1)+'</div><h2>'+esc(q.q)+'</h2><div class="mcq-options">'+q.options.map((x,i)=>'<button class="mcq-option" data-i="'+i+'"><span>'+String.fromCharCode(65+i)+'</span><b>'+esc(x)+'</b></button>').join("")+'</div><div id="feedback" class="mcq-feedback hidden"></div><button id="nextQuestion" class="primary hidden">Next Question →</button></div>';area.querySelectorAll(".mcq-option").forEach((b,i)=>b.onclick=()=>answer(i))}
function answer(i){const q=questions[index],buttons=[...area.querySelectorAll(".mcq-option")],correct=q.options.indexOf(q.answer),feedback=document.getElementById("feedback");buttons.forEach(b=>b.disabled=true);if(i===correct){score++;buttons[i].classList.add("correct");feedback.innerHTML="<strong>✓ Correct!</strong><br>"+esc(q.answer);feedback.className="mcq-feedback correct-feedback"}else{buttons[i].classList.add("wrong");buttons[correct].classList.add("correct");feedback.innerHTML="<strong>✗ Not quite.</strong><br>The correct answer is: <b>"+esc(q.answer)+"</b>";feedback.className="mcq-feedback wrong-feedback"}const next=document.getElementById("nextQuestion");next.classList.remove("hidden");next.onclick=()=>{index++;index<questions.length?show():finish()};feedback.scrollIntoView({behavior:"smooth",block:"nearest"})}
function finish(){progress.textContent="Complete";area.innerHTML='<div class="mcq-result"><div class="result-icon">🎉</div><h2>Chapter Quiz Complete!</h2><p>Sam scored <strong>'+score+' / '+questions.length+'</strong></p><button class="primary" id="retry">Try Again</button><a class="quiz-home" href="./">← Back to Bible Study</a></div>';document.getElementById("retry").onclick=()=>location.reload()}
if(!info||!events.length){area.innerHTML="<h2>Chapter not found.</h2><a class='quiz-home' href='./'>Return to Bible Study</a>"}else show();