let pdfDoc=null,currentPage=1,pages=[]; if(window.pdfjsLib){window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.js';}const $=id=>document.getElementById(id);const e={input:$("pdfInput"),drop:$("dropzone"),info:$("fileInfo"),create:$("createLesson"),status:$("status"),lesson:$("lessonSection"),title:$("slideTitle"),visual:$("visual"),flow:$("flow"),points:$("keyPoints"),discovery:$("discoveryText"),memory:$("memoryText"),progress:$("progress"),pageCount:$("pageCount"),counter:$("counter")};
function esc(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function visualFor(t){t=t.toLowerCase();if(t.includes("seed")||t.includes("plant"))return["🌱","🌿"];if(t.includes("water")||t.includes("rain"))return["💧","🌧️"];if(t.includes("butterfly"))return["🐛","🦋"];if(t.includes("earth")||t.includes("planet"))return["☀️","🌍"];if(t.includes("animal")||t.includes("bird"))return["🐾","🦋"];if(t.includes("space")||t.includes("moon"))return["🚀","🌙"];if(t.includes("flower"))return["🌸","🐝"];if(t.includes("food"))return["🌱","🍎"];return["📖","💡"];}
function points(text){text=text.replace(/\s+/g," ").trim();if(!text)return["This page contains an important idea.","Look at the visual to understand the concept.","Try to explain it in your own words."];let a=text.split(/(?<=[.!?])\s+/).filter(x=>x.length>20).slice(0,4);return a.length?a:[text.slice(0,150)];}
function slide(i,text){let v=visualFor(text),p=points(text),title=(text.trim().split(/[.!?]/)[0]||("Lesson page "+i)).slice(0,70);return{title:title,visual:v[0],second:v[1],points:p,discovery:p[0],memory:p[0].length<70?p[0]:"Remember the main idea: "+p[0].slice(0,65)+"…"};}
function render(){let s=pages[currentPage-1];if(!s)return;e.title.textContent=s.title;e.visual.textContent=s.visual;e.flow.textContent=s.visual+"  →  "+s.second;e.points.innerHTML=s.points.map(p=>"<li>"+esc(p)+"</li>").join("");e.discovery.textContent=s.discovery;e.memory.textContent=s.memory;e.counter.textContent=currentPage+" / "+pages.length;e.pageCount.textContent="Page "+currentPage+" of "+pages.length;e.progress.style.width=(currentPage/pages.length*100)+"%";}
async function readPdf(file){if(!window.pdfjsLib){e.status.textContent="The PDF reader is still loading. Please try again.";return;}try{e.status.textContent="Reading your PDF…";let b=await file.arrayBuffer();pdfDoc=await window.pdfjsLib.getDocument({data:b}).promise;pages=[];for(let i=1;i<=pdfDoc.numPages;i++){e.status.textContent="Reading page "+i+" of "+pdfDoc.numPages+"…";let p=await pdfDoc.getPage(i),tc=await p.getTextContent(),text=tc.items.map(x=>x.str).join(" ");pages.push(slide(i,text));}currentPage=1;render();e.lesson.classList.remove("hidden");e.status.textContent="Done — "+pages.length+" visual slides are ready.";}catch(err){e.status.textContent="I couldn't read that PDF. Please try another PDF.";console.error(err);}}
e.input.addEventListener("change",x=>{let f=x.target.files[0];if(!f)return;if(f.type!=="application/pdf"){e.status.textContent="Please choose a PDF file.";return}e.info.textContent="📄 "+f.name;e.info.classList.remove("hidden");e.create.classList.remove("hidden");e.create.onclick=()=>readPdf(f);});
["dragenter","dragover"].forEach(ev=>e.drop.addEventListener(ev,x=>{x.preventDefault();e.drop.classList.add("drag")}));["dragleave","drop"].forEach(ev=>e.drop.addEventListener(ev,x=>{x.preventDefault();e.drop.classList.remove("drag")}));e.drop.addEventListener("drop",x=>{let f=x.dataTransfer.files[0];if(f){e.input.files=x.dataTransfer.files;e.input.dispatchEvent(new Event("change"));}});
$("prevBtn").onclick=()=>{if(currentPage>1){currentPage--;render()}};$("nextBtn").onclick=()=>{if(currentPage<pages.length){currentPage++;render()}};$("firstBtn").onclick=()=>{currentPage=1;render()};$("lastBtn").onclick=()=>{currentPage=pages.length;render()};$("focusBtn").onclick=()=>{document.body.classList.toggle("focus-mode");$("focusBtn").textContent=document.body.classList.contains("focus-mode")?"↩ Exit Focus":"🎯 Focus Mode"};$("readBtn").onclick=()=>{if("speechSynthesis"in window){speechSynthesis.cancel();let s=pages[currentPage-1];speechSynthesis.speak(new SpeechSynthesisUtterance(s.title+". "+s.points.join(". ")));}};document.addEventListener("keydown",x=>{if(x.key==="ArrowRight")$("nextBtn").click();if(x.key==="ArrowLeft")$("prevBtn").click()});
function simSteps(t){t=t.toLowerCase();if(t.includes("seed")||t.includes("plant"))return["🌰 Seed","💧 Water","🌱 Sprout","🌿 Young plant","🌳 Growing plant"];if(t.includes("water cycle"))return["☀️ Evaporation","☁️ Condensation","🌧️ Rainfall","🌊 Collection"];if(t.includes("butterfly"))return["🥚 Egg","🐛 Caterpillar","🟢 Pupa","🦋 Butterfly"];if(t.includes("earth")&&t.includes("sun"))return["☀️ Sun","🌍 Earth","🔄 Orbit","🌌 Space"];if(t.includes("food chain"))return["🌱 Plant","🐛 Insect","🐸 Frog","🐍 Snake","🦅 Eagle"];if(t.includes("volcano"))return["🌋 Volcano","🔥 Heat","💨 Eruption","🌋 Lava"];return["💭 Idea","🔎 Explore","🧩 Connect","💡 Understand"];}
function simulate(){let text=$("simInput").value.trim();if(!text)return;let a=simSteps(text),html='<div class="sim-title">✨ '+esc(text)+'</div><div class="sim-steps">';a.forEach((x,i)=>{let z=x.split(" "),emoji=z.shift();html+='<div class="sim-step" style="animation-delay:'+(i*90)+'ms"><span class="emoji">'+emoji+"</span>"+esc(z.join(" "))+"</div>";if(i<a.length-1)html+='<span class="arrow">→</span>';});html+="</div>";$("simulation").innerHTML=html;$("simulation").classList.remove("hidden");}
document.querySelectorAll(".examples button").forEach(b=>b.onclick=()=>{$("simInput").value=b.dataset.example;simulate()});$("simulateBtn").onclick=simulate;