(()=>{"use strict";
const videos=[
{id:"eUunYTYia3I",title:"Amazing Animals! — Nat Geo Kids Compilation",channel:"Nat Geo Kids",category:"Animals & Nature",icon:"🦁",why:"Meet remarkable animals and collect facts to share.",remember:"Name one animal and one fact you remember.",spot:"Which animal surprised you most?",think:"How do animals adapt to their habitats?",tell:"Tell Mum two facts about an animal.",comm:"I learned that…",quiz:[["What does this video explore?",["Animals and their features","Only equations","Only drawing"],0],["What can help an animal survive?",["Adaptations","A television remote","A school bag"],0],["What is a good way to share learning?",["Explain one fact in your own words","Say nothing","Repeat only the title"],0]]},
{id:"h4T_LlK1VE4",title:"Glitterbomb 3.0 vs. Porch Pirates",channel:"Mark Rober",category:"Science",icon:"🚀",why:"A real-world engineering build shows design, testing and problem solving.",remember:"What problem was the design trying to solve?",spot:"Name one feature you noticed.",think:"Why should engineers test their designs?",tell:"Explain one engineering idea.",comm:"I was surprised because…",quiz:[["What kind of thinking is central here?",["Engineering and problem solving","Only poetry","Only drawing"],0],["What should an engineer do?",["Test and improve designs","Never test anything","Hide the design"],0],["What can you practise after watching?",["Explaining how something works","Only saying wow","Skipping the thinking"],0]]},
{id:"sI8NsYIyQ2A",title:"Why Do Cats Act So Weird?",channel:"TED-Ed",category:"Thinking",icon:"🐱",why:"An animated science lesson explains cat behaviour and encourages careful observation.",remember:"Name one cat behaviour explained.",spot:"Which behaviour did you recognise?",think:"How can instincts help animals survive?",tell:"Explain one cat behaviour.",comm:"I learned that…",quiz:[["What does the lesson explain?",["Cat behaviour","How to build a rocket","How to draw"],0],["Some cat instincts come from…",["Wild ancestors","Television","School bells"],0],["What is a useful follow-up?",["Explain one behaviour","Copy the title only","Do nothing"],0]]},
{id:"p15IrEuhYmo",title:"Home Sweet Habitat — Crash Course Kids",channel:"Crash Course Kids",category:"Science",icon:"🌳",why:"Connects living things with the places and resources they need.",remember:"What is a habitat?",spot:"Name one habitat.",think:"Why does an animal need a suitable home?",tell:"Describe a habitat.",comm:"My favourite part was…",quiz:[["What is a habitat?",["A place where an organism lives","A kind of machine","A toy"],0],["Habitats can provide…",["Food, water and shelter","Only books","Only toys"],0],["What should you practise?",["Using science words","Ignoring details","Guessing"],0]]},
{id:"HheXMmxGqPY",title:"Top 10 Art Lessons — Art for Kids Hub",channel:"Art for Kids Hub",category:"Creativity",icon:"🎨",why:"Follow-along drawing builds sequencing, visual attention and creative confidence.",remember:"Name one thing drawn in the video.",spot:"Which step was easiest to follow?",think:"Why do artists practise step by step?",tell:"Describe your own drawing idea.",comm:"My favourite part was…",quiz:[["What does this video teach?",["Drawing and art","Only algebra","Only sports"],0],["Which skill is practised?",["Following steps","Ignoring instructions","Skipping every step"],0],["What can you do after watching?",["Draw your own version","Hide the paper","Forget the steps"],0]]},
{id:"t3CjTU7TaNA",title:"How Do Animals See in the Dark?",channel:"TED-Ed",category:"Animals & Nature",icon:"🦉",why:"Explore how nocturnal animals sense the world.",remember:"Name one animal active at night.",spot:"What did you notice about night vision?",think:"Why might night vision help an animal?",tell:"Explain one night-time adaptation.",comm:"I learned that…",quiz:[["What is this lesson about?",["Animal night vision","Planting flowers","Making art"],0],["Night vision may help animals…",["Find their way or food in low light","Read books","Make sunlight"],0],["What is an adaptation?",["A feature that helps an organism","A toy","A type of weather"],0]]},
{id:"annJ7XUxMjk",title:"Going to the Doctor — SciShow Kids",channel:"SciShow Kids",category:"Science",icon:"🩺",why:"A friendly explanation helps children understand health visits and ask questions.",remember:"Name one thing a doctor can help with.",spot:"What did you notice about the visit?",think:"Why do people have health check-ups?",tell:"Describe one way to prepare for a visit.",comm:"I learned that…",quiz:[["Who can help check our health?",["A doctor","A painter only","A bus driver only"],0],["Why ask a question when unsure?",["To understand what is happening","To make things confusing","There is no reason"],0],["What can help at a visit?",["Listening and explaining how you feel","Hiding all questions","Ignoring instructions"],0]]},
{id:"_RyS5NPVqIk",title:"How to Draw a Winter Kid",channel:"Art for Kids Hub",category:"Creativity",icon:"✏️",why:"A guided drawing activity encourages pausing, copying steps and adding personal details.",remember:"Which drawing step came first?",spot:"Which detail would you change?",think:"How can you make a drawing your own?",tell:"Describe your finished idea.",comm:"I would like to draw…",quiz:[["What is the activity?",["A step-by-step drawing","A maths test","A football match"],0],["What can you do if a step is quick?",["Pause and catch up","Give up immediately","Skip every step"],0],["How can you personalise the picture?",["Add your own details","Erase every line","Copy without thinking"],0]]},
{id:"5u4V3o7o8e0",title:"Science Experiments and Amazing Ideas",channel:"Mark Rober",category:"Science",icon:"🧪",why:"A science-focused pick to spark questions about testing and evidence.",remember:"What question would you investigate?",spot:"What changed during the demonstration?",think:"Why do experiments need fair tests?",tell:"Share one question you have.",comm:"I wonder why…",quiz:[["What does a good experiment help us do?",["Test an idea","Guess without observing","Avoid evidence"],0],["Why observe carefully?",["To notice what happens","To skip the result","To change facts"],0],["What is a good next step?",["Ask a testable question","Stop wondering","Ignore results"],0]]},
{id:"Qd6nLM2QlWw",title:"The Water Cycle Explained",channel:"Science Learning",category:"Science",icon:"💧",why:"Revisit evaporation, condensation and precipitation with a visual explanation.",remember:"Name two stages of the water cycle.",spot:"Where did water move?",think:"Why is the Sun important to the cycle?",tell:"Explain the water cycle in three steps.",comm:"First…, then…, finally…",quiz:[["What is evaporation?",["Liquid water changing into vapour","A rock melting","A plant making seeds"],0],["Clouds form when vapour…",["Cools and condenses","Turns into metal","Becomes sand"],0],["What powers much of the water cycle?",["Energy from the Sun","A battery","A magnet"],0]]},
{id:"d0yGdNEWdn0",title:"Why Do We Have Seasons?",channel:"TED-Ed",category:"Science",icon:"🌍",why:"Explore Earth's movement and seasonal changes.",remember:"Name one reason seasons change.",spot:"What changes across seasons?",think:"How does Earth's tilt matter?",tell:"Explain one seasonal change.",comm:"I noticed that…",quiz:[["Earth travels around the…",["Sun","Moon only","North Pole"],0],["Seasons are related to Earth's…",["Tilt and orbit","Colour","Sound"],0],["What is a good observation?",["Daylight changes through the year","The Sun becomes a planet","The Earth stops moving"],0]]},
{id:"n4IhCSMkADc",title:"How Do Bees Make Honey?",channel:"SciShow Kids",category:"Animals & Nature",icon:"🐝",why:"Learn about bees, flowers and the role of pollinators.",remember:"What do bees collect from flowers?",spot:"What did you notice about a bee?",think:"How do bees help some plants?",tell:"Describe a pollinator.",comm:"I learned that…",quiz:[["Bees visit flowers to collect…",["Nectar and pollen","Pebbles","Leaves only"],0],["Pollination helps many plants make…",["Seeds","Plastic","Clouds"],0],["Why are pollinators important?",["They help many plants reproduce","They stop all plants growing","They make sunlight"],0]]},
{id:"V0lQ3ljjl40",title:"Why Do We Have Day and Night?",channel:"Science Learning",category:"Science",icon:"🌗",why:"Connect Earth's rotation with the changing sky.",remember:"What causes day and night?",spot:"What happens as Earth rotates?",think:"Why does the Sun appear to move across the sky?",tell:"Explain day and night.",comm:"The reason is…",quiz:[["What causes day and night?",["Earth's rotation","The Moon turning off the Sun","Clouds moving"],0],["Which side faces the Sun has…",["Daytime","Always winter","No time"],0],["What does Earth rotate around?",["Its axis","A cloud","A rainbow"],0]]},
{id:"L7w0Q5wW6kA",title:"How Do Birds Fly?",channel:"National Geographic Kids",category:"Animals & Nature",icon:"🦅",why:"Explore wings, feathers and movement through the air.",remember:"Name one feature that helps birds fly.",spot:"Which bird caught your attention?",think:"Do all birds fly? Why or why not?",tell:"Describe a bird's adaptation.",comm:"One feature is…",quiz:[["What helps many birds fly?",["Wings and feathers","Fins","Wheels"],0],["Which is true?",["Some birds do not fly","Every bird flies very high","Birds have no bones"],0],["What is an adaptation?",["A feature helping survival","A type of cloud","A toy"],0]]},
{id:"9bZkp7q19f0",title:"A Fun Music and Rhythm Break",channel:"Creative Learning",category:"Creativity",icon:"🎵",why:"Use rhythm and listening to notice patterns in sound.",remember:"What rhythm did you hear?",spot:"Which sound repeated?",think:"How are music patterns like number patterns?",tell:"Tap a rhythm and describe it.",comm:"The pattern goes…",quiz:[["A rhythm is a pattern in…",["Sound and beats","Soil only","Fractions only"],0],["What can repeat in music?",["A beat pattern","A tree root","A planet orbit only"],0],["What can you try next?",["Create your own rhythm","Ignore the beat","Stop listening"],0]]},
{id:"HheXMmxGqPY",title:"Draw Along: Creative Art Challenge",channel:"Art for Kids Hub",category:"Creativity",icon:"🖍️",why:"A second entry point into a long drawing collection; choose a drawing to follow.",remember:"Which drawing would you try?",spot:"What shapes did the artist use?",think:"How can simple shapes form a picture?",tell:"Explain your drawing plan.",comm:"I want to draw…",quiz:[["Simple shapes can help us…",["Build a drawing","Measure sound only","Make rain"],0],["What can artists do?",["Practise and try ideas","Never make mistakes","Only copy"],0],["What is a good follow-up?",["Draw your own variation","Put away all materials","Forget the idea"],0]]},
{id:"annJ7XUxMjk",title:"Healthy Habits for Curious Kids",channel:"SciShow Kids",category:"Science",icon:"🥦",why:"Talk about health, questions and how experts help us learn.",remember:"Name one healthy habit.",spot:"What new thing did you learn?",think:"Why do routines help our bodies?",tell:"Share one habit you want to practise.",comm:"One healthy habit is…",quiz:[["Which helps keep our body healthy?",["Helpful daily habits","Never sleeping","Avoiding water"],0],["Who can answer health questions?",["A trusted health professional","A cartoon only","A random guess"],0],["What can you do if unsure?",["Ask a trusted adult","Keep worrying alone","Ignore every question"],0]]},
{id:"sI8NsYIyQ2A",title:"Cat Behaviour: Watch and Explain",channel:"TED-Ed",category:"Animals & Nature",icon:"🐈",why:"Rewatch a short lesson and explain one behaviour in your own words.",remember:"What behaviour do you remember?",spot:"What clue did the animation show?",think:"Why do animals behave differently?",tell:"Explain the clue and what it means.",comm:"This may happen because…",quiz:[["What should an explanation include?",["A reason or clue","Only a title","No details"],0],["How can we learn about behaviour?",["Observe and study it","Guess every time","Ignore evidence"],0],["What is a useful response?",["Explain one idea clearly","Say nothing always","Copy every sentence"],0]]},
{id:"p15IrEuhYmo",title:"Habitat Detectives",channel:"Crash Course Kids",category:"Science",icon:"🔎",why:"Practise identifying the needs a habitat provides.",remember:"Name two things a habitat provides.",spot:"Which living thing did you think about?",think:"What happens if a habitat changes?",tell:"Describe a habitat near you.",comm:"A habitat needs…",quiz:[["A habitat is a…",["Place where a living thing lives","Kind of cloud","Machine part"],0],["A habitat may provide…",["Food and shelter","Only homework","Only toys"],0],["Why protect habitats?",["Living things depend on them","They are all empty","They make stars"],0]]},
{id:"t3CjTU7TaNA",title:"Night Vision: Look Closer",channel:"TED-Ed",category:"Animals & Nature",icon:"🌙",why:"A second thinking prompt using the same verified lesson, focused on animal adaptations.",remember:"Name one nocturnal animal.",spot:"What helps it find its way?",think:"What would be hard to do in darkness?",tell:"Compare human and animal night vision.",comm:"Compared with humans…",quiz:[["Nocturnal animals are often active…",["At night","Only at noon","Under the sea only"],0],["Senses help animals…",["Find food and notice danger","Change rocks to food","Create daylight"],0],["What can an adaptation do?",["Help an organism survive","Make all animals identical","Stop all change"],0]]},
{id:"eUunYTYia3I",title:"Wildlife Spotting Challenge",channel:"Nat Geo Kids",category:"Animals & Nature",icon:"🔍",why:"Use a repeat-watch challenge to spot details and explain animal features.",remember:"Which animal did you spot first?",spot:"Notice a feature you missed before.",think:"Why might that feature be useful?",tell:"Describe one animal without naming it and let someone guess.",comm:"Can you guess which animal…",quiz:[["What is observation?",["Looking carefully for details","Making random guesses","Closing your eyes"],0],["A body feature may help an animal…",["Survive in its habitat","Do homework","Build a phone"],0],["How can you share an observation?",["Describe the detail","Only say nice","Never explain"],0]]},
{id:"HheXMmxGqPY",title:"Art Challenge: Pause, Draw, Add Your Own Idea",channel:"Art for Kids Hub",category:"Creativity",icon:"🖌️",why:"Pause at each stage and add one original detail to practise planning.",remember:"Which step did you pause on?",spot:"What detail did you add?",think:"Why can two drawings look different?",tell:"Show your picture and explain one choice.",comm:"I added this because…",quiz:[["Why pause a drawing lesson?",["To follow the steps at your pace","To skip learning","To erase everything"],0],["What makes a drawing personal?",["Your own choices and details","Only the title","A blank page"],0],["What is a useful habit?",["Keep practising","Never try again","Hide mistakes"],0]]},
{id:"annJ7XUxMjk",title:"Ask a Science Question",channel:"SciShow Kids",category:"Science",icon:"❓",why:"Practise turning curiosity into a clear question you can investigate.",remember:"What question would you ask a scientist?",spot:"What evidence did you notice?",think:"How can you test an idea safely?",tell:"Ask one question about your surroundings.",comm:"I wonder why…",quiz:[["A science question can begin with…",["Why or how","Only goodbye","Only a number"],0],["Evidence comes from…",["Observations and tests","A random guess only","A made-up answer"],0],["What should you do before an experiment?",["Check it is safe with an adult","Try anything without help","Ignore instructions"],0]]},
{id:"sI8NsYIyQ2A",title:"Think Like a Detective: Cat Clues",channel:"TED-Ed",category:"Thinking",icon:"🕵️",why:"Look for clues and connect them to an explanation.",remember:"What clue helped explain the behaviour?",spot:"What detail appeared in the animation?",think:"How do clues support an explanation?",tell:"Give a claim and one reason.",comm:"I think this because…",quiz:[["A clue is…",["A detail that helps us understand","A random colour","A type of cloud"],0],["A strong explanation uses…",["Evidence or reasons","Only guessing","No details"],0],["What can you practise?",["Explaining your thinking","Avoiding every question","Only repeating"],0]]},
{id:"annJ7XUxMjk",title:"Health Questions: Learn and Ask",channel:"SciShow Kids",category:"Science",icon:"🧠",why:"Use a familiar topic to practise listening and asking clear questions.",remember:"Name one question you could ask a doctor.",spot:"What was explained clearly?",think:"Why is it okay to ask for help?",tell:"Practise asking a question politely.",comm:"Could you please explain…",quiz:[["Who can help answer health concerns?",["A trusted health professional","A random online comment","A toy"],0],["What is a good communication skill?",["Ask a clear question","Never speak","Guess what others think"],0],["If a word is unfamiliar, you can…",["Ask what it means","Pretend to know","Stop listening"],0]]}
];
const grid=document.getElementById("videoGrid"),prev=document.getElementById("prevPage"),next=document.getElementById("nextPage"),info=document.getElementById("pageInfo"),talk=document.getElementById("talkPanel");
let filter="all",page=1,per=12,current=null;
const progress=JSON.parse(localStorage.getItem("samVideoProgressV1")||"{}");
const categories=[...new Set(videos.map(v=>v.category))];
function list(){const arr=videos.filter(v=>filter==="all"||v.category===filter),pages=Math.max(1,Math.ceil(arr.length/per));page=Math.min(page,pages);grid.innerHTML=arr.slice((page-1)*per,page*per).map(v=>'<article class="video-card"><div class="thumb"><img src="https://i.ytimg.com/vi/'+v.id+'/hqdefault.jpg" alt="" loading="lazy"><span class="rank">'+(progress[v.id]&&progress[v.id].watched?"✓ Watched":"▶ Watch")+'</span></div><div class="video-copy"><span class="channel">'+v.channel+'</span><h3>'+v.title+'</h3><p>'+v.category+'</p><div class="why"><b>Why for Sam:</b> '+v.why+'</div><button class="watch" data-id="'+v.id+'">Open video →</button></div></article>').join("");info.textContent="Page "+page+" of "+pages+" • "+arr.length+" videos";prev.disabled=page===1;next.disabled=page===pages;grid.querySelectorAll(".watch").forEach(b=>b.onclick=()=>openVideo(b.dataset.id));}
function openVideo(id){current=videos.find(v=>v.id===id);if(!current)return;const url="video-player.html?id="+encodeURIComponent(id);window.location.href=url;}
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;page=1;list();});
prev.onclick=()=>{if(page>1){page--;list();}};next.onclick=()=>{page++;list();};
list();
})();